### ISSUE TITLE
правки Task (TaskList, Task, TaskRecipient, TaskButtons)

### ISSUE THREAD

**Issue by marussia1996** [ya-pomogau/frontend#145]

**Comment by marussia1996** [comment]
Правок много, если за это возьмется несколько человек будьте готовы, что нужно будет сначала поработать над пропсами Task и TaskList вместе, после чего разделится на подзадачи.
**TaskList**

- [x] сделать передачу item в TaskItem вместо тысячи пропсов 
- [x] для чего тянуть isStatusActive={isStatusActive} аж в TaskButton? Кажется от этого можно избавится
- [x] "Вы пока не можете создавать заявку. Дождитесь подтверждения администратора" вынести в константу (shared/libs/constants)
- [ ] изменить storybook в связи с изменениями(добавить examples)

**Task** 

- [x] сделать передачу item в TaskItem вместо тысячи пропсов
- [ ] confirmed && completed заменить на новые поля объекта
- [x] использовать деструктуризацию для полей таски переданных через объект item
- [x] TaskRecipient: заменить volunteer === null ? false : true на правильное условие при передачи пропса connection={volunteer === null ? false : true}
- [ ] TaskButtons: заменить completed conflict на правильные поля
- [x] добавить стиль на background таски в зависимости от нажатых кнопок пользователем (подтверждена как выполненная/не выполненная) (см. миро)
- [ ] изменить storybook в связи с изменениями(добавить examples)

**TaskInfo**

- [x] поправить стили отображения времени при бессрочной заявки в соответствии с макетом

**TaskRecipient**

- [x] TaskRecipient переименовать в TaskUser
- [x] переименовать в name & phone. В зависимости от роли текущего пользователя отображается информация либо волонтера либо реципиента
recipientName?: string;
recipientPhoneNumber?: string;
- [x] Если отображаются таски реципиента, то в зависимости от поля volunteer должна отображаться либо пустая рамка аватара, либо аватар и информация.
- [x] disabled кнопок привести к логике описанной в миро

**TaskButtons**
- [x]  логика отображения работы кнопок должна соответствовать миро доске
- [x] в зависимости от роли, на некоторых попапах будет разный текст, добавить текст + логику (см. миро)

Типы связанные с таской вы можете найти по пути **src/entities/task/types.ts**
**db.json - почищен**, поэтому для тестирования придется создавать новые записи.
так как ветка fix/task-type еще не залита в dev, то создавайте свои ветки из нее.
Если будут вопросы - пишите
